# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a47760c66ce6e894aea4b07e82b9be3d949c4c84ed95fe459b8f2606e157d1c37d2d3242ebf0233d9f1f581b9adf49a2ca74c716c20059b4ae6a2a170bf7fd9

test:
  secret_key_base: 0b69c00910162444eea11e97c6e5909e4011f20965ef7447ef5d0811de55c880648b300739e331c8cddab2928edcf199ecf08b787210c7761c41b30ec5b36d69

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
 secret_key_base: <%= ENV["STAGING_SECRET_KEY_BASE"] %>

production:
 secret_key_base: <%= ENV["PRODUCTION_SECRET_KEY_BASE"] %>
